[project]
name = "helpers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nesterov-BA", email = "nesterov.boris123@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "black>=26.5.1",
    "mbake>=1.4.6",
    "python-lsp-server>=1.15.0",
    "ruff>=0.16.7",
]

[project.scripts]
helpers = "helpers:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
